name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonar-scan:
    uses: nirojasmar/base-workflows/.github/workflows/sonar-scan.yml@main
    with:
      project_key: "hobio"
      scanner_type: "dotnet"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORG: ${{ secrets.SONAR_ORG }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build...
        run: echo "Building images..."
